// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordShopAppDAL.Context;

#nullable disable

namespace RecordShopAppDAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240715190342_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary1.Concerete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DropDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("Nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Password")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2314),
                            DropDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "BC4A26B5A4ABEDFD6D1A3F78E5AADA2162C4B1A908DE7A70E1B3A0B26E27E6E6",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("ClassLibrary1.Concerete.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("Nvarchar(100)");

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DisctountRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("DropDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumName = "Thriller",
                            Artist = "Michael Jackson",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2424),
                            DisctountRate = 10m,
                            Genre = 0,
                            Price = 29.99m,
                            ReleaseDate = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 2,
                            AlbumName = "Back in Black",
                            Artist = "AC/DC",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2429),
                            DisctountRate = 15m,
                            Genre = 1,
                            Price = 24.99m,
                            ReleaseDate = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 3,
                            AlbumName = "The Dark Side of the Moon",
                            Artist = "Pink Floyd",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2431),
                            DisctountRate = 20m,
                            Genre = 1,
                            Price = 19.99m,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Discontunied"
                        },
                        new
                        {
                            Id = 4,
                            AlbumName = "The Wall",
                            Artist = "Pink Floyd",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2432),
                            DisctountRate = 5m,
                            Genre = 1,
                            Price = 22.99m,
                            ReleaseDate = new DateTime(1979, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 5,
                            AlbumName = "Abbey Road",
                            Artist = "The Beatles",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2434),
                            DisctountRate = 12m,
                            Genre = 1,
                            Price = 27.99m,
                            ReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 6,
                            AlbumName = "Hotel California",
                            Artist = "Eagles",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2436),
                            DisctountRate = 15m,
                            Genre = 1,
                            Price = 25.99m,
                            ReleaseDate = new DateTime(1976, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 7,
                            AlbumName = "Led Zeppelin IV",
                            Artist = "Led Zeppelin",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2465),
                            DisctountRate = 10m,
                            Genre = 1,
                            Price = 21.99m,
                            ReleaseDate = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 8,
                            AlbumName = "Born to Run",
                            Artist = "Bruce Springsteen",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2466),
                            DisctountRate = 8m,
                            Genre = 1,
                            Price = 23.99m,
                            ReleaseDate = new DateTime(1975, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 9,
                            AlbumName = "Rumours",
                            Artist = "Fleetwood Mac",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2468),
                            DisctountRate = 10m,
                            Genre = 1,
                            Price = 24.99m,
                            ReleaseDate = new DateTime(1977, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Discontunied"
                        },
                        new
                        {
                            Id = 10,
                            AlbumName = "Nevermind",
                            Artist = "Nirvana",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2469),
                            DisctountRate = 5m,
                            Genre = 1,
                            Price = 19.99m,
                            ReleaseDate = new DateTime(1991, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 11,
                            AlbumName = "Sgt. Pepper's Lonely Hearts Club Band",
                            Artist = "The Beatles",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2471),
                            DisctountRate = 10m,
                            Genre = 1,
                            Price = 26.99m,
                            ReleaseDate = new DateTime(1967, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 12,
                            AlbumName = "A Night at the Opera",
                            Artist = "Queen",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2472),
                            DisctountRate = 7m,
                            Genre = 1,
                            Price = 22.99m,
                            ReleaseDate = new DateTime(1975, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 13,
                            AlbumName = "The Joshua Tree",
                            Artist = "U2",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2474),
                            DisctountRate = 12m,
                            Genre = 1,
                            Price = 24.99m,
                            ReleaseDate = new DateTime(1987, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 14,
                            AlbumName = "Who's Next",
                            Artist = "The Who",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2476),
                            DisctountRate = 10m,
                            Genre = 1,
                            Price = 21.99m,
                            ReleaseDate = new DateTime(1971, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Discontunied"
                        },
                        new
                        {
                            Id = 15,
                            AlbumName = "Purple Rain",
                            Artist = "Prince",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2478),
                            DisctountRate = 8m,
                            Genre = 0,
                            Price = 22.99m,
                            ReleaseDate = new DateTime(1984, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 16,
                            AlbumName = "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
                            Artist = "David Bowie",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2480),
                            DisctountRate = 15m,
                            Genre = 1,
                            Price = 20.99m,
                            ReleaseDate = new DateTime(1972, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 17,
                            AlbumName = "Sticky Fingers",
                            Artist = "The Rolling Stones",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2481),
                            DisctountRate = 10m,
                            Genre = 1,
                            Price = 23.99m,
                            ReleaseDate = new DateTime(1971, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 18,
                            AlbumName = "The Velvet Underground & Nico",
                            Artist = "The Velvet Underground",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2483),
                            DisctountRate = 12m,
                            Genre = 1,
                            Price = 21.99m,
                            ReleaseDate = new DateTime(1967, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Discontunied"
                        },
                        new
                        {
                            Id = 19,
                            AlbumName = "OK Computer",
                            Artist = "Radiohead",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2484),
                            DisctountRate = 8m,
                            Genre = 1,
                            Price = 22.99m,
                            ReleaseDate = new DateTime(1997, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        },
                        new
                        {
                            Id = 20,
                            AlbumName = "The Miseducation of Lauryn Hill",
                            Artist = "Lauryn Hill",
                            CreateDate = new DateTime(2024, 7, 15, 22, 3, 41, 870, DateTimeKind.Local).AddTicks(2486),
                            DisctountRate = 10m,
                            Genre = 0,
                            Price = 24.99m,
                            ReleaseDate = new DateTime(1998, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnSale"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
